env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended

overrides:
  - env:
      node: true
    files:
      - '.eslintrc.{js,cjs}'
    parserOptions:
      sourceType: script

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react

rules:
  jsx-a11y/control-has-associated-label: 0
  jsx-a11y/anchor-is-valid: 0
  react/jsx-props-no-spreading: 0
  react/state-in-constructor: 0
  react/react-in-jsx-scope: 0
  react/function-component-definition: 0
  react/no-unused-class-component-methods: 0
  react/no-unstable-nested-components: 0
  no-nonoctal-decimal-escape: 0
  no-unsafe-optional-chaining: 0
  default-param-last: 0
  object-curly-newline: 0
  react/prop-types: 0
  comma-dangle: 0
  template-curly-spacing: 0
  indent: 0
  import/prefer-default-export: 0
  no-unused-vars: 1
  no-multiple-empty-lines: 1
  import/no-unresolved: 0
  camelcase: 0
